version: '3'

vars:
  IMAGE_NAME: 'us-central1-docker.pkg.dev/healthy-earth-389717/verizon-drift-monitoring/dataproc-job-env:latest'
  GCP_PROJECT: 'healthy-earth-389717'
  GCP_REGION: 'us-central1'
  GCP_DATAPROC_CLUSTER: 'verizon-drift-monitoring'
  SPARK_JOB_PROPERTIES: './spark_job.properties'

tasks:
  build:
    cmds:
      - docker build --platform linux/amd64 -t {{.IMAGE_NAME}} .

  push:
    cmds:
      - docker push {{.IMAGE_NAME}}

  deploy:
    cmds:
      - python create_database_tables.py {{.CLI_ARGS}}
      - python create_dashboard_json.py {{.CLI_ARGS}}

  transform:
    cmds:
      - python spark_transformation.py {{.CLI_ARGS}}

  submit-transform:
    cmds:
      - gcloud dataproc --project={{.GCP_PROJECT}}
        jobs submit pyspark spark_transformation.py
        --cluster={{.GCP_DATAPROC_CLUSTER}}
        --region={{.GCP_REGION}}
        --properties-file={{.SPARK_JOB_PROPERTIES}}
        --files=.env.dataproc
        -- {{.CLI_ARGS}}

  test:
    cmds:
      - echo {{.CLI_ARGS}}
      - echo {{.SHELL}}