{
 "title": "Drift Monitoring Dashboard",
 "description": "Example python-generated dashboard",
 "time": { "from": "now-3d", "to": "now" },
 "panels": [
  {
   "title": "Negative Scores Distribution",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", score \nFROM neg_score_table \nWHERE \"timestamp\" BETWEEN $__timeFrom() AND $__timeTo() \nORDER BY \"timestamp\" DESC "
    }
   ]
  },
  {
   "title": "Positive Scores Distribution",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", score \nFROM pos_score_table \nWHERE \"timestamp\" BETWEEN $__timeFrom() AND $__timeTo() \nORDER BY \"timestamp\" DESC "
    }
   ]
  },
  {
   "title": "PSI",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT * FROM psi_table ORDER BY \"timestamp\" DESC "
    }
   ]
  },
  {
   "title": "Confusion Matrix",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", tp AS \"TP\", fp AS \"FP\", fn AS \"FN\", tn AS \"TN\"\nFROM confusion_table\nWHERE \"timestamp\" BETWEEN $__timeFrom() AND $__timeTo()"
    }
   ]
  },
  {
   "title": "Accuracy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT * FROM acc_table ORDER BY \"timestamp\" DESC "
    }
   ]
  },
  {
   "title": "Precision",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT * FROM prec_table ORDER BY \"timestamp\" DESC "
    }
   ]
  },
  {
   "title": "Recall",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT * FROM rec_table ORDER BY \"timestamp\" DESC "
    }
   ]
  },
  {
   "title": "F1 Score",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT * FROM f1_table ORDER BY \"timestamp\" DESC "
    }
   ]
  },
  {
   "title": "ROC Curve",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "WITH filtered AS (\n    SELECT * FROM roc_fp_table WHERE \"timestamp\" BETWEEN $__timeFrom() AND $__timeTo()\n)\nSELECT '0' AS \"score\", AVG(_0) AS fpr FROM filtered\nUNION ALL\nSELECT '1', AVG(_1) FROM filtered\nUNION ALL\nSELECT '2', AVG(_2) FROM filtered\nUNION ALL\nSELECT '3', AVG(_3) FROM filtered\nUNION ALL\nSELECT '4', AVG(_4) FROM filtered\nUNION ALL\nSELECT '5', AVG(_5) FROM filtered\nUNION ALL\nSELECT '6', AVG(_6) FROM filtered\nUNION ALL\nSELECT '7', AVG(_7) FROM filtered\nUNION ALL\nSELECT '8', AVG(_8) FROM filtered\nUNION ALL\nSELECT '9', AVG(_9) FROM filtered\nUNION ALL\nSELECT '10', AVG(_10) FROM filtered\nUNION ALL\nSELECT '11', AVG(_11) FROM filtered\nUNION ALL\nSELECT '12', AVG(_12) FROM filtered\nUNION ALL\nSELECT '13', AVG(_13) FROM filtered\nUNION ALL\nSELECT '14', AVG(_14) FROM filtered\nUNION ALL\nSELECT '15', AVG(_15) FROM filtered\nUNION ALL\nSELECT '16', AVG(_16) FROM filtered\nUNION ALL\nSELECT '17', AVG(_17) FROM filtered\nUNION ALL\nSELECT '18', AVG(_18) FROM filtered\nUNION ALL\nSELECT '19', AVG(_19) FROM filtered\nUNION ALL\nSELECT '20', AVG(_20) FROM filtered\nUNION ALL\nSELECT '21', AVG(_21) FROM filtered\nUNION ALL\nSELECT '22', AVG(_22) FROM filtered\nUNION ALL\nSELECT '23', AVG(_23) FROM filtered\nUNION ALL\nSELECT '24', AVG(_24) FROM filtered\nUNION ALL\nSELECT '25', AVG(_25) FROM filtered\nUNION ALL\nSELECT '26', AVG(_26) FROM filtered\nUNION ALL\nSELECT '27', AVG(_27) FROM filtered\nUNION ALL\nSELECT '28', AVG(_28) FROM filtered\nUNION ALL\nSELECT '29', AVG(_29) FROM filtered\nUNION ALL\nSELECT '30', AVG(_30) FROM filtered\nUNION ALL\nSELECT '31', AVG(_31) FROM filtered\nUNION ALL\nSELECT '32', AVG(_32) FROM filtered\nUNION ALL\nSELECT '33', AVG(_33) FROM filtered\nUNION ALL\nSELECT '34', AVG(_34) FROM filtered\nUNION ALL\nSELECT '35', AVG(_35) FROM filtered\nUNION ALL\nSELECT '36', AVG(_36) FROM filtered\nUNION ALL\nSELECT '37', AVG(_37) FROM filtered\nUNION ALL\nSELECT '38', AVG(_38) FROM filtered\nUNION ALL\nSELECT '39', AVG(_39) FROM filtered\nUNION ALL\nSELECT '40', AVG(_40) FROM filtered\nUNION ALL\nSELECT '41', AVG(_41) FROM filtered\nUNION ALL\nSELECT '42', AVG(_42) FROM filtered\nUNION ALL\nSELECT '43', AVG(_43) FROM filtered\nUNION ALL\nSELECT '44', AVG(_44) FROM filtered\nUNION ALL\nSELECT '45', AVG(_45) FROM filtered\nUNION ALL\nSELECT '46', AVG(_46) FROM filtered\nUNION ALL\nSELECT '47', AVG(_47) FROM filtered\nUNION ALL\nSELECT '48', AVG(_48) FROM filtered\nUNION ALL\nSELECT '49', AVG(_49) FROM filtered\nUNION ALL\nSELECT '50', AVG(_50) FROM filtered\nUNION ALL\nSELECT '51', AVG(_51) FROM filtered\nUNION ALL\nSELECT '52', AVG(_52) FROM filtered\nUNION ALL\nSELECT '53', AVG(_53) FROM filtered\nUNION ALL\nSELECT '54', AVG(_54) FROM filtered\nUNION ALL\nSELECT '55', AVG(_55) FROM filtered\nUNION ALL\nSELECT '56', AVG(_56) FROM filtered\nUNION ALL\nSELECT '57', AVG(_57) FROM filtered\nUNION ALL\nSELECT '58', AVG(_58) FROM filtered\nUNION ALL\nSELECT '59', AVG(_59) FROM filtered\nUNION ALL\nSELECT '60', AVG(_60) FROM filtered\nUNION ALL\nSELECT '61', AVG(_61) FROM filtered\nUNION ALL\nSELECT '62', AVG(_62) FROM filtered\nUNION ALL\nSELECT '63', AVG(_63) FROM filtered\nUNION ALL\nSELECT '64', AVG(_64) FROM filtered\nUNION ALL\nSELECT '65', AVG(_65) FROM filtered\nUNION ALL\nSELECT '66', AVG(_66) FROM filtered\nUNION ALL\nSELECT '67', AVG(_67) FROM filtered\nUNION ALL\nSELECT '68', AVG(_68) FROM filtered\nUNION ALL\nSELECT '69', AVG(_69) FROM filtered\nUNION ALL\nSELECT '70', AVG(_70) FROM filtered\nUNION ALL\nSELECT '71', AVG(_71) FROM filtered\nUNION ALL\nSELECT '72', AVG(_72) FROM filtered\nUNION ALL\nSELECT '73', AVG(_73) FROM filtered\nUNION ALL\nSELECT '74', AVG(_74) FROM filtered\nUNION ALL\nSELECT '75', AVG(_75) FROM filtered\nUNION ALL\nSELECT '76', AVG(_76) FROM filtered\nUNION ALL\nSELECT '77', AVG(_77) FROM filtered\nUNION ALL\nSELECT '78', AVG(_78) FROM filtered\nUNION ALL\nSELECT '79', AVG(_79) FROM filtered\nUNION ALL\nSELECT '80', AVG(_80) FROM filtered\nUNION ALL\nSELECT '81', AVG(_81) FROM filtered\nUNION ALL\nSELECT '82', AVG(_82) FROM filtered\nUNION ALL\nSELECT '83', AVG(_83) FROM filtered\nUNION ALL\nSELECT '84', AVG(_84) FROM filtered\nUNION ALL\nSELECT '85', AVG(_85) FROM filtered\nUNION ALL\nSELECT '86', AVG(_86) FROM filtered\nUNION ALL\nSELECT '87', AVG(_87) FROM filtered\nUNION ALL\nSELECT '88', AVG(_88) FROM filtered\nUNION ALL\nSELECT '89', AVG(_89) FROM filtered\nUNION ALL\nSELECT '90', AVG(_90) FROM filtered\nUNION ALL\nSELECT '91', AVG(_91) FROM filtered\nUNION ALL\nSELECT '92', AVG(_92) FROM filtered\nUNION ALL\nSELECT '93', AVG(_93) FROM filtered\nUNION ALL\nSELECT '94', AVG(_94) FROM filtered\nUNION ALL\nSELECT '95', AVG(_95) FROM filtered\nUNION ALL\nSELECT '96', AVG(_96) FROM filtered\nUNION ALL\nSELECT '97', AVG(_97) FROM filtered\nUNION ALL\nSELECT '98', AVG(_98) FROM filtered\nUNION ALL\nSELECT '99', AVG(_99) FROM filtered\nUNION ALL\nSELECT '100', 0.0;\n"
    },
    {
     "rawSql": "WITH filtered AS (\n    SELECT * FROM roc_tp_table WHERE \"timestamp\" BETWEEN $__timeFrom() AND $__timeTo()\n)\nSELECT '0' AS \"score\", AVG(_0) AS tpr FROM filtered\nUNION ALL\nSELECT '1', AVG(_1) FROM filtered\nUNION ALL\nSELECT '2', AVG(_2) FROM filtered\nUNION ALL\nSELECT '3', AVG(_3) FROM filtered\nUNION ALL\nSELECT '4', AVG(_4) FROM filtered\nUNION ALL\nSELECT '5', AVG(_5) FROM filtered\nUNION ALL\nSELECT '6', AVG(_6) FROM filtered\nUNION ALL\nSELECT '7', AVG(_7) FROM filtered\nUNION ALL\nSELECT '8', AVG(_8) FROM filtered\nUNION ALL\nSELECT '9', AVG(_9) FROM filtered\nUNION ALL\nSELECT '10', AVG(_10) FROM filtered\nUNION ALL\nSELECT '11', AVG(_11) FROM filtered\nUNION ALL\nSELECT '12', AVG(_12) FROM filtered\nUNION ALL\nSELECT '13', AVG(_13) FROM filtered\nUNION ALL\nSELECT '14', AVG(_14) FROM filtered\nUNION ALL\nSELECT '15', AVG(_15) FROM filtered\nUNION ALL\nSELECT '16', AVG(_16) FROM filtered\nUNION ALL\nSELECT '17', AVG(_17) FROM filtered\nUNION ALL\nSELECT '18', AVG(_18) FROM filtered\nUNION ALL\nSELECT '19', AVG(_19) FROM filtered\nUNION ALL\nSELECT '20', AVG(_20) FROM filtered\nUNION ALL\nSELECT '21', AVG(_21) FROM filtered\nUNION ALL\nSELECT '22', AVG(_22) FROM filtered\nUNION ALL\nSELECT '23', AVG(_23) FROM filtered\nUNION ALL\nSELECT '24', AVG(_24) FROM filtered\nUNION ALL\nSELECT '25', AVG(_25) FROM filtered\nUNION ALL\nSELECT '26', AVG(_26) FROM filtered\nUNION ALL\nSELECT '27', AVG(_27) FROM filtered\nUNION ALL\nSELECT '28', AVG(_28) FROM filtered\nUNION ALL\nSELECT '29', AVG(_29) FROM filtered\nUNION ALL\nSELECT '30', AVG(_30) FROM filtered\nUNION ALL\nSELECT '31', AVG(_31) FROM filtered\nUNION ALL\nSELECT '32', AVG(_32) FROM filtered\nUNION ALL\nSELECT '33', AVG(_33) FROM filtered\nUNION ALL\nSELECT '34', AVG(_34) FROM filtered\nUNION ALL\nSELECT '35', AVG(_35) FROM filtered\nUNION ALL\nSELECT '36', AVG(_36) FROM filtered\nUNION ALL\nSELECT '37', AVG(_37) FROM filtered\nUNION ALL\nSELECT '38', AVG(_38) FROM filtered\nUNION ALL\nSELECT '39', AVG(_39) FROM filtered\nUNION ALL\nSELECT '40', AVG(_40) FROM filtered\nUNION ALL\nSELECT '41', AVG(_41) FROM filtered\nUNION ALL\nSELECT '42', AVG(_42) FROM filtered\nUNION ALL\nSELECT '43', AVG(_43) FROM filtered\nUNION ALL\nSELECT '44', AVG(_44) FROM filtered\nUNION ALL\nSELECT '45', AVG(_45) FROM filtered\nUNION ALL\nSELECT '46', AVG(_46) FROM filtered\nUNION ALL\nSELECT '47', AVG(_47) FROM filtered\nUNION ALL\nSELECT '48', AVG(_48) FROM filtered\nUNION ALL\nSELECT '49', AVG(_49) FROM filtered\nUNION ALL\nSELECT '50', AVG(_50) FROM filtered\nUNION ALL\nSELECT '51', AVG(_51) FROM filtered\nUNION ALL\nSELECT '52', AVG(_52) FROM filtered\nUNION ALL\nSELECT '53', AVG(_53) FROM filtered\nUNION ALL\nSELECT '54', AVG(_54) FROM filtered\nUNION ALL\nSELECT '55', AVG(_55) FROM filtered\nUNION ALL\nSELECT '56', AVG(_56) FROM filtered\nUNION ALL\nSELECT '57', AVG(_57) FROM filtered\nUNION ALL\nSELECT '58', AVG(_58) FROM filtered\nUNION ALL\nSELECT '59', AVG(_59) FROM filtered\nUNION ALL\nSELECT '60', AVG(_60) FROM filtered\nUNION ALL\nSELECT '61', AVG(_61) FROM filtered\nUNION ALL\nSELECT '62', AVG(_62) FROM filtered\nUNION ALL\nSELECT '63', AVG(_63) FROM filtered\nUNION ALL\nSELECT '64', AVG(_64) FROM filtered\nUNION ALL\nSELECT '65', AVG(_65) FROM filtered\nUNION ALL\nSELECT '66', AVG(_66) FROM filtered\nUNION ALL\nSELECT '67', AVG(_67) FROM filtered\nUNION ALL\nSELECT '68', AVG(_68) FROM filtered\nUNION ALL\nSELECT '69', AVG(_69) FROM filtered\nUNION ALL\nSELECT '70', AVG(_70) FROM filtered\nUNION ALL\nSELECT '71', AVG(_71) FROM filtered\nUNION ALL\nSELECT '72', AVG(_72) FROM filtered\nUNION ALL\nSELECT '73', AVG(_73) FROM filtered\nUNION ALL\nSELECT '74', AVG(_74) FROM filtered\nUNION ALL\nSELECT '75', AVG(_75) FROM filtered\nUNION ALL\nSELECT '76', AVG(_76) FROM filtered\nUNION ALL\nSELECT '77', AVG(_77) FROM filtered\nUNION ALL\nSELECT '78', AVG(_78) FROM filtered\nUNION ALL\nSELECT '79', AVG(_79) FROM filtered\nUNION ALL\nSELECT '80', AVG(_80) FROM filtered\nUNION ALL\nSELECT '81', AVG(_81) FROM filtered\nUNION ALL\nSELECT '82', AVG(_82) FROM filtered\nUNION ALL\nSELECT '83', AVG(_83) FROM filtered\nUNION ALL\nSELECT '84', AVG(_84) FROM filtered\nUNION ALL\nSELECT '85', AVG(_85) FROM filtered\nUNION ALL\nSELECT '86', AVG(_86) FROM filtered\nUNION ALL\nSELECT '87', AVG(_87) FROM filtered\nUNION ALL\nSELECT '88', AVG(_88) FROM filtered\nUNION ALL\nSELECT '89', AVG(_89) FROM filtered\nUNION ALL\nSELECT '90', AVG(_90) FROM filtered\nUNION ALL\nSELECT '91', AVG(_91) FROM filtered\nUNION ALL\nSELECT '92', AVG(_92) FROM filtered\nUNION ALL\nSELECT '93', AVG(_93) FROM filtered\nUNION ALL\nSELECT '94', AVG(_94) FROM filtered\nUNION ALL\nSELECT '95', AVG(_95) FROM filtered\nUNION ALL\nSELECT '96', AVG(_96) FROM filtered\nUNION ALL\nSELECT '97', AVG(_97) FROM filtered\nUNION ALL\nSELECT '98', AVG(_98) FROM filtered\nUNION ALL\nSELECT '99', AVG(_99) FROM filtered\nUNION ALL\nSELECT '100', 0.0;\n"
    }
   ]
  },
  {
   "title": "AUROC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT * FROM auroc_table ORDER BY \"timestamp\" DESC "
    }
   ]
  },
  {
   "title": "PR Curve",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "WITH filtered AS (\n    SELECT * FROM prc_prec_table WHERE \"timestamp\" BETWEEN $__timeFrom() AND $__timeTo()\n)\nSELECT '0' AS \"score\", AVG(_0) AS tpr FROM filtered\nUNION ALL\nSELECT '1', AVG(_1) FROM filtered\nUNION ALL\nSELECT '2', AVG(_2) FROM filtered\nUNION ALL\nSELECT '3', AVG(_3) FROM filtered\nUNION ALL\nSELECT '4', AVG(_4) FROM filtered\nUNION ALL\nSELECT '5', AVG(_5) FROM filtered\nUNION ALL\nSELECT '6', AVG(_6) FROM filtered\nUNION ALL\nSELECT '7', AVG(_7) FROM filtered\nUNION ALL\nSELECT '8', AVG(_8) FROM filtered\nUNION ALL\nSELECT '9', AVG(_9) FROM filtered\nUNION ALL\nSELECT '10', AVG(_10) FROM filtered\nUNION ALL\nSELECT '11', AVG(_11) FROM filtered\nUNION ALL\nSELECT '12', AVG(_12) FROM filtered\nUNION ALL\nSELECT '13', AVG(_13) FROM filtered\nUNION ALL\nSELECT '14', AVG(_14) FROM filtered\nUNION ALL\nSELECT '15', AVG(_15) FROM filtered\nUNION ALL\nSELECT '16', AVG(_16) FROM filtered\nUNION ALL\nSELECT '17', AVG(_17) FROM filtered\nUNION ALL\nSELECT '18', AVG(_18) FROM filtered\nUNION ALL\nSELECT '19', AVG(_19) FROM filtered\nUNION ALL\nSELECT '20', AVG(_20) FROM filtered\nUNION ALL\nSELECT '21', AVG(_21) FROM filtered\nUNION ALL\nSELECT '22', AVG(_22) FROM filtered\nUNION ALL\nSELECT '23', AVG(_23) FROM filtered\nUNION ALL\nSELECT '24', AVG(_24) FROM filtered\nUNION ALL\nSELECT '25', AVG(_25) FROM filtered\nUNION ALL\nSELECT '26', AVG(_26) FROM filtered\nUNION ALL\nSELECT '27', AVG(_27) FROM filtered\nUNION ALL\nSELECT '28', AVG(_28) FROM filtered\nUNION ALL\nSELECT '29', AVG(_29) FROM filtered\nUNION ALL\nSELECT '30', AVG(_30) FROM filtered\nUNION ALL\nSELECT '31', AVG(_31) FROM filtered\nUNION ALL\nSELECT '32', AVG(_32) FROM filtered\nUNION ALL\nSELECT '33', AVG(_33) FROM filtered\nUNION ALL\nSELECT '34', AVG(_34) FROM filtered\nUNION ALL\nSELECT '35', AVG(_35) FROM filtered\nUNION ALL\nSELECT '36', AVG(_36) FROM filtered\nUNION ALL\nSELECT '37', AVG(_37) FROM filtered\nUNION ALL\nSELECT '38', AVG(_38) FROM filtered\nUNION ALL\nSELECT '39', AVG(_39) FROM filtered\nUNION ALL\nSELECT '40', AVG(_40) FROM filtered\nUNION ALL\nSELECT '41', AVG(_41) FROM filtered\nUNION ALL\nSELECT '42', AVG(_42) FROM filtered\nUNION ALL\nSELECT '43', AVG(_43) FROM filtered\nUNION ALL\nSELECT '44', AVG(_44) FROM filtered\nUNION ALL\nSELECT '45', AVG(_45) FROM filtered\nUNION ALL\nSELECT '46', AVG(_46) FROM filtered\nUNION ALL\nSELECT '47', AVG(_47) FROM filtered\nUNION ALL\nSELECT '48', AVG(_48) FROM filtered\nUNION ALL\nSELECT '49', AVG(_49) FROM filtered\nUNION ALL\nSELECT '50', AVG(_50) FROM filtered\nUNION ALL\nSELECT '51', AVG(_51) FROM filtered\nUNION ALL\nSELECT '52', AVG(_52) FROM filtered\nUNION ALL\nSELECT '53', AVG(_53) FROM filtered\nUNION ALL\nSELECT '54', AVG(_54) FROM filtered\nUNION ALL\nSELECT '55', AVG(_55) FROM filtered\nUNION ALL\nSELECT '56', AVG(_56) FROM filtered\nUNION ALL\nSELECT '57', AVG(_57) FROM filtered\nUNION ALL\nSELECT '58', AVG(_58) FROM filtered\nUNION ALL\nSELECT '59', AVG(_59) FROM filtered\nUNION ALL\nSELECT '60', AVG(_60) FROM filtered\nUNION ALL\nSELECT '61', AVG(_61) FROM filtered\nUNION ALL\nSELECT '62', AVG(_62) FROM filtered\nUNION ALL\nSELECT '63', AVG(_63) FROM filtered\nUNION ALL\nSELECT '64', AVG(_64) FROM filtered\nUNION ALL\nSELECT '65', AVG(_65) FROM filtered\nUNION ALL\nSELECT '66', AVG(_66) FROM filtered\nUNION ALL\nSELECT '67', AVG(_67) FROM filtered\nUNION ALL\nSELECT '68', AVG(_68) FROM filtered\nUNION ALL\nSELECT '69', AVG(_69) FROM filtered\nUNION ALL\nSELECT '70', AVG(_70) FROM filtered\nUNION ALL\nSELECT '71', AVG(_71) FROM filtered\nUNION ALL\nSELECT '72', AVG(_72) FROM filtered\nUNION ALL\nSELECT '73', AVG(_73) FROM filtered\nUNION ALL\nSELECT '74', AVG(_74) FROM filtered\nUNION ALL\nSELECT '75', AVG(_75) FROM filtered\nUNION ALL\nSELECT '76', AVG(_76) FROM filtered\nUNION ALL\nSELECT '77', AVG(_77) FROM filtered\nUNION ALL\nSELECT '78', AVG(_78) FROM filtered\nUNION ALL\nSELECT '79', AVG(_79) FROM filtered\nUNION ALL\nSELECT '80', AVG(_80) FROM filtered\nUNION ALL\nSELECT '81', AVG(_81) FROM filtered\nUNION ALL\nSELECT '82', AVG(_82) FROM filtered\nUNION ALL\nSELECT '83', AVG(_83) FROM filtered\nUNION ALL\nSELECT '84', AVG(_84) FROM filtered\nUNION ALL\nSELECT '85', AVG(_85) FROM filtered\nUNION ALL\nSELECT '86', AVG(_86) FROM filtered\nUNION ALL\nSELECT '87', AVG(_87) FROM filtered\nUNION ALL\nSELECT '88', AVG(_88) FROM filtered\nUNION ALL\nSELECT '89', AVG(_89) FROM filtered\nUNION ALL\nSELECT '90', AVG(_90) FROM filtered\nUNION ALL\nSELECT '91', AVG(_91) FROM filtered\nUNION ALL\nSELECT '92', AVG(_92) FROM filtered\nUNION ALL\nSELECT '93', AVG(_93) FROM filtered\nUNION ALL\nSELECT '94', AVG(_94) FROM filtered\nUNION ALL\nSELECT '95', AVG(_95) FROM filtered\nUNION ALL\nSELECT '96', AVG(_96) FROM filtered\nUNION ALL\nSELECT '97', AVG(_97) FROM filtered\nUNION ALL\nSELECT '98', AVG(_98) FROM filtered\nUNION ALL\nSELECT '99', AVG(_99) FROM filtered\nUNION ALL\nSELECT '100', 1.0;\n"
    },
    {
     "rawSql": "WITH filtered AS (\n    SELECT * FROM prc_rec_table WHERE \"timestamp\" BETWEEN $__timeFrom() AND $__timeTo()\n)\nSELECT '0' AS \"score\", AVG(_0) AS tpr FROM filtered\nUNION ALL\nSELECT '1', AVG(_1) FROM filtered\nUNION ALL\nSELECT '2', AVG(_2) FROM filtered\nUNION ALL\nSELECT '3', AVG(_3) FROM filtered\nUNION ALL\nSELECT '4', AVG(_4) FROM filtered\nUNION ALL\nSELECT '5', AVG(_5) FROM filtered\nUNION ALL\nSELECT '6', AVG(_6) FROM filtered\nUNION ALL\nSELECT '7', AVG(_7) FROM filtered\nUNION ALL\nSELECT '8', AVG(_8) FROM filtered\nUNION ALL\nSELECT '9', AVG(_9) FROM filtered\nUNION ALL\nSELECT '10', AVG(_10) FROM filtered\nUNION ALL\nSELECT '11', AVG(_11) FROM filtered\nUNION ALL\nSELECT '12', AVG(_12) FROM filtered\nUNION ALL\nSELECT '13', AVG(_13) FROM filtered\nUNION ALL\nSELECT '14', AVG(_14) FROM filtered\nUNION ALL\nSELECT '15', AVG(_15) FROM filtered\nUNION ALL\nSELECT '16', AVG(_16) FROM filtered\nUNION ALL\nSELECT '17', AVG(_17) FROM filtered\nUNION ALL\nSELECT '18', AVG(_18) FROM filtered\nUNION ALL\nSELECT '19', AVG(_19) FROM filtered\nUNION ALL\nSELECT '20', AVG(_20) FROM filtered\nUNION ALL\nSELECT '21', AVG(_21) FROM filtered\nUNION ALL\nSELECT '22', AVG(_22) FROM filtered\nUNION ALL\nSELECT '23', AVG(_23) FROM filtered\nUNION ALL\nSELECT '24', AVG(_24) FROM filtered\nUNION ALL\nSELECT '25', AVG(_25) FROM filtered\nUNION ALL\nSELECT '26', AVG(_26) FROM filtered\nUNION ALL\nSELECT '27', AVG(_27) FROM filtered\nUNION ALL\nSELECT '28', AVG(_28) FROM filtered\nUNION ALL\nSELECT '29', AVG(_29) FROM filtered\nUNION ALL\nSELECT '30', AVG(_30) FROM filtered\nUNION ALL\nSELECT '31', AVG(_31) FROM filtered\nUNION ALL\nSELECT '32', AVG(_32) FROM filtered\nUNION ALL\nSELECT '33', AVG(_33) FROM filtered\nUNION ALL\nSELECT '34', AVG(_34) FROM filtered\nUNION ALL\nSELECT '35', AVG(_35) FROM filtered\nUNION ALL\nSELECT '36', AVG(_36) FROM filtered\nUNION ALL\nSELECT '37', AVG(_37) FROM filtered\nUNION ALL\nSELECT '38', AVG(_38) FROM filtered\nUNION ALL\nSELECT '39', AVG(_39) FROM filtered\nUNION ALL\nSELECT '40', AVG(_40) FROM filtered\nUNION ALL\nSELECT '41', AVG(_41) FROM filtered\nUNION ALL\nSELECT '42', AVG(_42) FROM filtered\nUNION ALL\nSELECT '43', AVG(_43) FROM filtered\nUNION ALL\nSELECT '44', AVG(_44) FROM filtered\nUNION ALL\nSELECT '45', AVG(_45) FROM filtered\nUNION ALL\nSELECT '46', AVG(_46) FROM filtered\nUNION ALL\nSELECT '47', AVG(_47) FROM filtered\nUNION ALL\nSELECT '48', AVG(_48) FROM filtered\nUNION ALL\nSELECT '49', AVG(_49) FROM filtered\nUNION ALL\nSELECT '50', AVG(_50) FROM filtered\nUNION ALL\nSELECT '51', AVG(_51) FROM filtered\nUNION ALL\nSELECT '52', AVG(_52) FROM filtered\nUNION ALL\nSELECT '53', AVG(_53) FROM filtered\nUNION ALL\nSELECT '54', AVG(_54) FROM filtered\nUNION ALL\nSELECT '55', AVG(_55) FROM filtered\nUNION ALL\nSELECT '56', AVG(_56) FROM filtered\nUNION ALL\nSELECT '57', AVG(_57) FROM filtered\nUNION ALL\nSELECT '58', AVG(_58) FROM filtered\nUNION ALL\nSELECT '59', AVG(_59) FROM filtered\nUNION ALL\nSELECT '60', AVG(_60) FROM filtered\nUNION ALL\nSELECT '61', AVG(_61) FROM filtered\nUNION ALL\nSELECT '62', AVG(_62) FROM filtered\nUNION ALL\nSELECT '63', AVG(_63) FROM filtered\nUNION ALL\nSELECT '64', AVG(_64) FROM filtered\nUNION ALL\nSELECT '65', AVG(_65) FROM filtered\nUNION ALL\nSELECT '66', AVG(_66) FROM filtered\nUNION ALL\nSELECT '67', AVG(_67) FROM filtered\nUNION ALL\nSELECT '68', AVG(_68) FROM filtered\nUNION ALL\nSELECT '69', AVG(_69) FROM filtered\nUNION ALL\nSELECT '70', AVG(_70) FROM filtered\nUNION ALL\nSELECT '71', AVG(_71) FROM filtered\nUNION ALL\nSELECT '72', AVG(_72) FROM filtered\nUNION ALL\nSELECT '73', AVG(_73) FROM filtered\nUNION ALL\nSELECT '74', AVG(_74) FROM filtered\nUNION ALL\nSELECT '75', AVG(_75) FROM filtered\nUNION ALL\nSELECT '76', AVG(_76) FROM filtered\nUNION ALL\nSELECT '77', AVG(_77) FROM filtered\nUNION ALL\nSELECT '78', AVG(_78) FROM filtered\nUNION ALL\nSELECT '79', AVG(_79) FROM filtered\nUNION ALL\nSELECT '80', AVG(_80) FROM filtered\nUNION ALL\nSELECT '81', AVG(_81) FROM filtered\nUNION ALL\nSELECT '82', AVG(_82) FROM filtered\nUNION ALL\nSELECT '83', AVG(_83) FROM filtered\nUNION ALL\nSELECT '84', AVG(_84) FROM filtered\nUNION ALL\nSELECT '85', AVG(_85) FROM filtered\nUNION ALL\nSELECT '86', AVG(_86) FROM filtered\nUNION ALL\nSELECT '87', AVG(_87) FROM filtered\nUNION ALL\nSELECT '88', AVG(_88) FROM filtered\nUNION ALL\nSELECT '89', AVG(_89) FROM filtered\nUNION ALL\nSELECT '90', AVG(_90) FROM filtered\nUNION ALL\nSELECT '91', AVG(_91) FROM filtered\nUNION ALL\nSELECT '92', AVG(_92) FROM filtered\nUNION ALL\nSELECT '93', AVG(_93) FROM filtered\nUNION ALL\nSELECT '94', AVG(_94) FROM filtered\nUNION ALL\nSELECT '95', AVG(_95) FROM filtered\nUNION ALL\nSELECT '96', AVG(_96) FROM filtered\nUNION ALL\nSELECT '97', AVG(_97) FROM filtered\nUNION ALL\nSELECT '98', AVG(_98) FROM filtered\nUNION ALL\nSELECT '99', AVG(_99) FROM filtered\nUNION ALL\nSELECT '100', 0.0;\n"
    }
   ]
  },
  {
   "title": "AUPRC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT * FROM auprc_table ORDER BY \"timestamp\" DESC "
    }
   ]
  },
  {
   "title": "TPR / Recall on Thresholds",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT * FROM roc_tp_table ORDER BY \"timestamp\" DESC "
    }
   ]
  },
  {
   "title": "TPR / Recall Gain",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT * FROM roc_tp_diff_table ORDER BY \"timestamp\" DESC "
    }
   ]
  },
  {
   "title": "Precision on Thresholds",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "rawSql": "SELECT * FROM prc_prec_table ORDER BY \"timestamp\" DESC "
    }
   ]
  },
  {
   "title": "Precision Gain",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "rawSql": "SELECT * FROM prc_prec_diff_table ORDER BY \"timestamp\" DESC "
    }
   ]
  },
  {
   "title": "FPR on Thresholds",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "rawSql": "SELECT * FROM roc_fp_table ORDER BY \"timestamp\" DESC "
    }
   ]
  },
  {
   "title": "FPR Gain",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "rawSql": "SELECT * FROM roc_fp_diff_table ORDER BY \"timestamp\" DESC "
    }
   ]
  },
  {
   "title": "Lift",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "rawSql": "SELECT * FROM lift_table ORDER BY \"timestamp\" DESC "
    }
   ]
  },
  {
   "title": "Lift Gain",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "rawSql": "SELECT * FROM lift_diff_table ORDER BY \"timestamp\" DESC "
    }
   ]
  }
 ]
}