create table acc_table
(
    timestamp timestamp not null
        primary key,
    baseline  double precision,
    realtime  double precision
);

create table prec_table
(
    timestamp timestamp not null
        primary key,
    baseline  double precision,
    realtime  double precision
);

create table rec_table
(
    timestamp timestamp not null
        primary key,
    baseline  double precision,
    realtime  double precision
);

create table f1_table
(
    timestamp timestamp not null
        primary key,
    baseline  double precision,
    realtime  double precision
);

create table auroc_table
(
    timestamp timestamp not null
        primary key,
    baseline  double precision,
    realtime  double precision
);

create table auprc_table
(
    timestamp timestamp not null
        primary key,
    baseline  double precision,
    realtime  double precision
);

create table psi_table
(
    timestamp timestamp not null
        primary key,
    value     double precision
);

create table roc_fp_table
(
    timestamp timestamp not null
        primary key,
    _0        double precision,
    _1        double precision,
    _2        double precision,
    _3        double precision,
    _4        double precision,
    _5        double precision,
    _6        double precision,
    _7        double precision,
    _8        double precision,
    _9        double precision,
    _10       double precision,
    _11       double precision,
    _12       double precision,
    _13       double precision,
    _14       double precision,
    _15       double precision,
    _16       double precision,
    _17       double precision,
    _18       double precision,
    _19       double precision,
    _20       double precision,
    _21       double precision,
    _22       double precision,
    _23       double precision,
    _24       double precision,
    _25       double precision,
    _26       double precision,
    _27       double precision,
    _28       double precision,
    _29       double precision,
    _30       double precision,
    _31       double precision,
    _32       double precision,
    _33       double precision,
    _34       double precision,
    _35       double precision,
    _36       double precision,
    _37       double precision,
    _38       double precision,
    _39       double precision,
    _40       double precision,
    _41       double precision,
    _42       double precision,
    _43       double precision,
    _44       double precision,
    _45       double precision,
    _46       double precision,
    _47       double precision,
    _48       double precision,
    _49       double precision,
    _50       double precision,
    _51       double precision,
    _52       double precision,
    _53       double precision,
    _54       double precision,
    _55       double precision,
    _56       double precision,
    _57       double precision,
    _58       double precision,
    _59       double precision,
    _60       double precision,
    _61       double precision,
    _62       double precision,
    _63       double precision,
    _64       double precision,
    _65       double precision,
    _66       double precision,
    _67       double precision,
    _68       double precision,
    _69       double precision,
    _70       double precision,
    _71       double precision,
    _72       double precision,
    _73       double precision,
    _74       double precision,
    _75       double precision,
    _76       double precision,
    _77       double precision,
    _78       double precision,
    _79       double precision,
    _80       double precision,
    _81       double precision,
    _82       double precision,
    _83       double precision,
    _84       double precision,
    _85       double precision,
    _86       double precision,
    _87       double precision,
    _88       double precision,
    _89       double precision,
    _90       double precision,
    _91       double precision,
    _92       double precision,
    _93       double precision,
    _94       double precision,
    _95       double precision,
    _96       double precision,
    _97       double precision,
    _98       double precision,
    _99       double precision
);

create table roc_fp_diff_table
(
    timestamp timestamp not null
        primary key,
    _0        double precision,
    _1        double precision,
    _2        double precision,
    _3        double precision,
    _4        double precision,
    _5        double precision,
    _6        double precision,
    _7        double precision,
    _8        double precision,
    _9        double precision,
    _10       double precision,
    _11       double precision,
    _12       double precision,
    _13       double precision,
    _14       double precision,
    _15       double precision,
    _16       double precision,
    _17       double precision,
    _18       double precision,
    _19       double precision,
    _20       double precision,
    _21       double precision,
    _22       double precision,
    _23       double precision,
    _24       double precision,
    _25       double precision,
    _26       double precision,
    _27       double precision,
    _28       double precision,
    _29       double precision,
    _30       double precision,
    _31       double precision,
    _32       double precision,
    _33       double precision,
    _34       double precision,
    _35       double precision,
    _36       double precision,
    _37       double precision,
    _38       double precision,
    _39       double precision,
    _40       double precision,
    _41       double precision,
    _42       double precision,
    _43       double precision,
    _44       double precision,
    _45       double precision,
    _46       double precision,
    _47       double precision,
    _48       double precision,
    _49       double precision,
    _50       double precision,
    _51       double precision,
    _52       double precision,
    _53       double precision,
    _54       double precision,
    _55       double precision,
    _56       double precision,
    _57       double precision,
    _58       double precision,
    _59       double precision,
    _60       double precision,
    _61       double precision,
    _62       double precision,
    _63       double precision,
    _64       double precision,
    _65       double precision,
    _66       double precision,
    _67       double precision,
    _68       double precision,
    _69       double precision,
    _70       double precision,
    _71       double precision,
    _72       double precision,
    _73       double precision,
    _74       double precision,
    _75       double precision,
    _76       double precision,
    _77       double precision,
    _78       double precision,
    _79       double precision,
    _80       double precision,
    _81       double precision,
    _82       double precision,
    _83       double precision,
    _84       double precision,
    _85       double precision,
    _86       double precision,
    _87       double precision,
    _88       double precision,
    _89       double precision,
    _90       double precision,
    _91       double precision,
    _92       double precision,
    _93       double precision,
    _94       double precision,
    _95       double precision,
    _96       double precision,
    _97       double precision,
    _98       double precision,
    _99       double precision
);

create table roc_tp_table
(
    timestamp timestamp not null
        primary key,
    _0        double precision,
    _1        double precision,
    _2        double precision,
    _3        double precision,
    _4        double precision,
    _5        double precision,
    _6        double precision,
    _7        double precision,
    _8        double precision,
    _9        double precision,
    _10       double precision,
    _11       double precision,
    _12       double precision,
    _13       double precision,
    _14       double precision,
    _15       double precision,
    _16       double precision,
    _17       double precision,
    _18       double precision,
    _19       double precision,
    _20       double precision,
    _21       double precision,
    _22       double precision,
    _23       double precision,
    _24       double precision,
    _25       double precision,
    _26       double precision,
    _27       double precision,
    _28       double precision,
    _29       double precision,
    _30       double precision,
    _31       double precision,
    _32       double precision,
    _33       double precision,
    _34       double precision,
    _35       double precision,
    _36       double precision,
    _37       double precision,
    _38       double precision,
    _39       double precision,
    _40       double precision,
    _41       double precision,
    _42       double precision,
    _43       double precision,
    _44       double precision,
    _45       double precision,
    _46       double precision,
    _47       double precision,
    _48       double precision,
    _49       double precision,
    _50       double precision,
    _51       double precision,
    _52       double precision,
    _53       double precision,
    _54       double precision,
    _55       double precision,
    _56       double precision,
    _57       double precision,
    _58       double precision,
    _59       double precision,
    _60       double precision,
    _61       double precision,
    _62       double precision,
    _63       double precision,
    _64       double precision,
    _65       double precision,
    _66       double precision,
    _67       double precision,
    _68       double precision,
    _69       double precision,
    _70       double precision,
    _71       double precision,
    _72       double precision,
    _73       double precision,
    _74       double precision,
    _75       double precision,
    _76       double precision,
    _77       double precision,
    _78       double precision,
    _79       double precision,
    _80       double precision,
    _81       double precision,
    _82       double precision,
    _83       double precision,
    _84       double precision,
    _85       double precision,
    _86       double precision,
    _87       double precision,
    _88       double precision,
    _89       double precision,
    _90       double precision,
    _91       double precision,
    _92       double precision,
    _93       double precision,
    _94       double precision,
    _95       double precision,
    _96       double precision,
    _97       double precision,
    _98       double precision,
    _99       double precision
);

create table roc_tp_diff_table
(
    timestamp timestamp not null
        primary key,
    _0        double precision,
    _1        double precision,
    _2        double precision,
    _3        double precision,
    _4        double precision,
    _5        double precision,
    _6        double precision,
    _7        double precision,
    _8        double precision,
    _9        double precision,
    _10       double precision,
    _11       double precision,
    _12       double precision,
    _13       double precision,
    _14       double precision,
    _15       double precision,
    _16       double precision,
    _17       double precision,
    _18       double precision,
    _19       double precision,
    _20       double precision,
    _21       double precision,
    _22       double precision,
    _23       double precision,
    _24       double precision,
    _25       double precision,
    _26       double precision,
    _27       double precision,
    _28       double precision,
    _29       double precision,
    _30       double precision,
    _31       double precision,
    _32       double precision,
    _33       double precision,
    _34       double precision,
    _35       double precision,
    _36       double precision,
    _37       double precision,
    _38       double precision,
    _39       double precision,
    _40       double precision,
    _41       double precision,
    _42       double precision,
    _43       double precision,
    _44       double precision,
    _45       double precision,
    _46       double precision,
    _47       double precision,
    _48       double precision,
    _49       double precision,
    _50       double precision,
    _51       double precision,
    _52       double precision,
    _53       double precision,
    _54       double precision,
    _55       double precision,
    _56       double precision,
    _57       double precision,
    _58       double precision,
    _59       double precision,
    _60       double precision,
    _61       double precision,
    _62       double precision,
    _63       double precision,
    _64       double precision,
    _65       double precision,
    _66       double precision,
    _67       double precision,
    _68       double precision,
    _69       double precision,
    _70       double precision,
    _71       double precision,
    _72       double precision,
    _73       double precision,
    _74       double precision,
    _75       double precision,
    _76       double precision,
    _77       double precision,
    _78       double precision,
    _79       double precision,
    _80       double precision,
    _81       double precision,
    _82       double precision,
    _83       double precision,
    _84       double precision,
    _85       double precision,
    _86       double precision,
    _87       double precision,
    _88       double precision,
    _89       double precision,
    _90       double precision,
    _91       double precision,
    _92       double precision,
    _93       double precision,
    _94       double precision,
    _95       double precision,
    _96       double precision,
    _97       double precision,
    _98       double precision,
    _99       double precision
);

create table prc_prec_table
(
    timestamp timestamp not null
        primary key,
    _0        double precision,
    _1        double precision,
    _2        double precision,
    _3        double precision,
    _4        double precision,
    _5        double precision,
    _6        double precision,
    _7        double precision,
    _8        double precision,
    _9        double precision,
    _10       double precision,
    _11       double precision,
    _12       double precision,
    _13       double precision,
    _14       double precision,
    _15       double precision,
    _16       double precision,
    _17       double precision,
    _18       double precision,
    _19       double precision,
    _20       double precision,
    _21       double precision,
    _22       double precision,
    _23       double precision,
    _24       double precision,
    _25       double precision,
    _26       double precision,
    _27       double precision,
    _28       double precision,
    _29       double precision,
    _30       double precision,
    _31       double precision,
    _32       double precision,
    _33       double precision,
    _34       double precision,
    _35       double precision,
    _36       double precision,
    _37       double precision,
    _38       double precision,
    _39       double precision,
    _40       double precision,
    _41       double precision,
    _42       double precision,
    _43       double precision,
    _44       double precision,
    _45       double precision,
    _46       double precision,
    _47       double precision,
    _48       double precision,
    _49       double precision,
    _50       double precision,
    _51       double precision,
    _52       double precision,
    _53       double precision,
    _54       double precision,
    _55       double precision,
    _56       double precision,
    _57       double precision,
    _58       double precision,
    _59       double precision,
    _60       double precision,
    _61       double precision,
    _62       double precision,
    _63       double precision,
    _64       double precision,
    _65       double precision,
    _66       double precision,
    _67       double precision,
    _68       double precision,
    _69       double precision,
    _70       double precision,
    _71       double precision,
    _72       double precision,
    _73       double precision,
    _74       double precision,
    _75       double precision,
    _76       double precision,
    _77       double precision,
    _78       double precision,
    _79       double precision,
    _80       double precision,
    _81       double precision,
    _82       double precision,
    _83       double precision,
    _84       double precision,
    _85       double precision,
    _86       double precision,
    _87       double precision,
    _88       double precision,
    _89       double precision,
    _90       double precision,
    _91       double precision,
    _92       double precision,
    _93       double precision,
    _94       double precision,
    _95       double precision,
    _96       double precision,
    _97       double precision,
    _98       double precision,
    _99       double precision
);

create table prc_prec_diff_table
(
    timestamp timestamp not null
        primary key,
    _0        double precision,
    _1        double precision,
    _2        double precision,
    _3        double precision,
    _4        double precision,
    _5        double precision,
    _6        double precision,
    _7        double precision,
    _8        double precision,
    _9        double precision,
    _10       double precision,
    _11       double precision,
    _12       double precision,
    _13       double precision,
    _14       double precision,
    _15       double precision,
    _16       double precision,
    _17       double precision,
    _18       double precision,
    _19       double precision,
    _20       double precision,
    _21       double precision,
    _22       double precision,
    _23       double precision,
    _24       double precision,
    _25       double precision,
    _26       double precision,
    _27       double precision,
    _28       double precision,
    _29       double precision,
    _30       double precision,
    _31       double precision,
    _32       double precision,
    _33       double precision,
    _34       double precision,
    _35       double precision,
    _36       double precision,
    _37       double precision,
    _38       double precision,
    _39       double precision,
    _40       double precision,
    _41       double precision,
    _42       double precision,
    _43       double precision,
    _44       double precision,
    _45       double precision,
    _46       double precision,
    _47       double precision,
    _48       double precision,
    _49       double precision,
    _50       double precision,
    _51       double precision,
    _52       double precision,
    _53       double precision,
    _54       double precision,
    _55       double precision,
    _56       double precision,
    _57       double precision,
    _58       double precision,
    _59       double precision,
    _60       double precision,
    _61       double precision,
    _62       double precision,
    _63       double precision,
    _64       double precision,
    _65       double precision,
    _66       double precision,
    _67       double precision,
    _68       double precision,
    _69       double precision,
    _70       double precision,
    _71       double precision,
    _72       double precision,
    _73       double precision,
    _74       double precision,
    _75       double precision,
    _76       double precision,
    _77       double precision,
    _78       double precision,
    _79       double precision,
    _80       double precision,
    _81       double precision,
    _82       double precision,
    _83       double precision,
    _84       double precision,
    _85       double precision,
    _86       double precision,
    _87       double precision,
    _88       double precision,
    _89       double precision,
    _90       double precision,
    _91       double precision,
    _92       double precision,
    _93       double precision,
    _94       double precision,
    _95       double precision,
    _96       double precision,
    _97       double precision,
    _98       double precision,
    _99       double precision
);

create table prc_rec_table
(
    timestamp timestamp not null
        primary key,
    _0        double precision,
    _1        double precision,
    _2        double precision,
    _3        double precision,
    _4        double precision,
    _5        double precision,
    _6        double precision,
    _7        double precision,
    _8        double precision,
    _9        double precision,
    _10       double precision,
    _11       double precision,
    _12       double precision,
    _13       double precision,
    _14       double precision,
    _15       double precision,
    _16       double precision,
    _17       double precision,
    _18       double precision,
    _19       double precision,
    _20       double precision,
    _21       double precision,
    _22       double precision,
    _23       double precision,
    _24       double precision,
    _25       double precision,
    _26       double precision,
    _27       double precision,
    _28       double precision,
    _29       double precision,
    _30       double precision,
    _31       double precision,
    _32       double precision,
    _33       double precision,
    _34       double precision,
    _35       double precision,
    _36       double precision,
    _37       double precision,
    _38       double precision,
    _39       double precision,
    _40       double precision,
    _41       double precision,
    _42       double precision,
    _43       double precision,
    _44       double precision,
    _45       double precision,
    _46       double precision,
    _47       double precision,
    _48       double precision,
    _49       double precision,
    _50       double precision,
    _51       double precision,
    _52       double precision,
    _53       double precision,
    _54       double precision,
    _55       double precision,
    _56       double precision,
    _57       double precision,
    _58       double precision,
    _59       double precision,
    _60       double precision,
    _61       double precision,
    _62       double precision,
    _63       double precision,
    _64       double precision,
    _65       double precision,
    _66       double precision,
    _67       double precision,
    _68       double precision,
    _69       double precision,
    _70       double precision,
    _71       double precision,
    _72       double precision,
    _73       double precision,
    _74       double precision,
    _75       double precision,
    _76       double precision,
    _77       double precision,
    _78       double precision,
    _79       double precision,
    _80       double precision,
    _81       double precision,
    _82       double precision,
    _83       double precision,
    _84       double precision,
    _85       double precision,
    _86       double precision,
    _87       double precision,
    _88       double precision,
    _89       double precision,
    _90       double precision,
    _91       double precision,
    _92       double precision,
    _93       double precision,
    _94       double precision,
    _95       double precision,
    _96       double precision,
    _97       double precision,
    _98       double precision,
    _99       double precision
);

create table prc_rec_diff_table
(
    timestamp timestamp not null
        primary key,
    _0        double precision,
    _1        double precision,
    _2        double precision,
    _3        double precision,
    _4        double precision,
    _5        double precision,
    _6        double precision,
    _7        double precision,
    _8        double precision,
    _9        double precision,
    _10       double precision,
    _11       double precision,
    _12       double precision,
    _13       double precision,
    _14       double precision,
    _15       double precision,
    _16       double precision,
    _17       double precision,
    _18       double precision,
    _19       double precision,
    _20       double precision,
    _21       double precision,
    _22       double precision,
    _23       double precision,
    _24       double precision,
    _25       double precision,
    _26       double precision,
    _27       double precision,
    _28       double precision,
    _29       double precision,
    _30       double precision,
    _31       double precision,
    _32       double precision,
    _33       double precision,
    _34       double precision,
    _35       double precision,
    _36       double precision,
    _37       double precision,
    _38       double precision,
    _39       double precision,
    _40       double precision,
    _41       double precision,
    _42       double precision,
    _43       double precision,
    _44       double precision,
    _45       double precision,
    _46       double precision,
    _47       double precision,
    _48       double precision,
    _49       double precision,
    _50       double precision,
    _51       double precision,
    _52       double precision,
    _53       double precision,
    _54       double precision,
    _55       double precision,
    _56       double precision,
    _57       double precision,
    _58       double precision,
    _59       double precision,
    _60       double precision,
    _61       double precision,
    _62       double precision,
    _63       double precision,
    _64       double precision,
    _65       double precision,
    _66       double precision,
    _67       double precision,
    _68       double precision,
    _69       double precision,
    _70       double precision,
    _71       double precision,
    _72       double precision,
    _73       double precision,
    _74       double precision,
    _75       double precision,
    _76       double precision,
    _77       double precision,
    _78       double precision,
    _79       double precision,
    _80       double precision,
    _81       double precision,
    _82       double precision,
    _83       double precision,
    _84       double precision,
    _85       double precision,
    _86       double precision,
    _87       double precision,
    _88       double precision,
    _89       double precision,
    _90       double precision,
    _91       double precision,
    _92       double precision,
    _93       double precision,
    _94       double precision,
    _95       double precision,
    _96       double precision,
    _97       double precision,
    _98       double precision,
    _99       double precision
);

create table lift_table
(
    timestamp timestamp not null
        primary key,
    decile_1  double precision,
    decile_2  double precision,
    decile_3  double precision,
    decile_4  double precision,
    decile_5  double precision,
    decile_6  double precision,
    decile_7  double precision,
    decile_8  double precision,
    decile_9  double precision,
    decile_10 double precision
);

create table lift_diff_table
(
    timestamp timestamp not null
        primary key,
    decile_1  double precision,
    decile_2  double precision,
    decile_3  double precision,
    decile_4  double precision,
    decile_5  double precision,
    decile_6  double precision,
    decile_7  double precision,
    decile_8  double precision,
    decile_9  double precision,
    decile_10 double precision
);

create table pos_score_table
(
    id        serial
        primary key,
    timestamp timestamp,
    value     double precision
);

create table neg_score_table
(
    id        serial
        primary key,
    timestamp timestamp,
    value     double precision
);

create table confusion_table
(
    timestamp timestamp not null
        primary key,
    tp        double precision,
    fp        double precision,
    tn        double precision,
    fn        double precision
);

