WITH filtered AS (
    SELECT * FROM roc_tp_table WHERE "timestamp" BETWEEN $__timeFrom() AND $__timeTo()
)
SELECT '0' AS "score", AVG(_0) AS tpr FROM filtered
UNION ALL
SELECT '1', AVG(_1) FROM filtered
UNION ALL
SELECT '2', AVG(_2) FROM filtered
UNION ALL
SELECT '3', AVG(_3) FROM filtered
UNION ALL
SELECT '4', AVG(_4) FROM filtered
UNION ALL
SELECT '5', AVG(_5) FROM filtered
UNION ALL
SELECT '6', AVG(_6) FROM filtered
UNION ALL
SELECT '7', AVG(_7) FROM filtered
UNION ALL
SELECT '8', AVG(_8) FROM filtered
UNION ALL
SELECT '9', AVG(_9) FROM filtered
UNION ALL
SELECT '10', AVG(_10) FROM filtered
UNION ALL
SELECT '11', AVG(_11) FROM filtered
UNION ALL
SELECT '12', AVG(_12) FROM filtered
UNION ALL
SELECT '13', AVG(_13) FROM filtered
UNION ALL
SELECT '14', AVG(_14) FROM filtered
UNION ALL
SELECT '15', AVG(_15) FROM filtered
UNION ALL
SELECT '16', AVG(_16) FROM filtered
UNION ALL
SELECT '17', AVG(_17) FROM filtered
UNION ALL
SELECT '18', AVG(_18) FROM filtered
UNION ALL
SELECT '19', AVG(_19) FROM filtered
UNION ALL
SELECT '20', AVG(_20) FROM filtered
UNION ALL
SELECT '21', AVG(_21) FROM filtered
UNION ALL
SELECT '22', AVG(_22) FROM filtered
UNION ALL
SELECT '23', AVG(_23) FROM filtered
UNION ALL
SELECT '24', AVG(_24) FROM filtered
UNION ALL
SELECT '25', AVG(_25) FROM filtered
UNION ALL
SELECT '26', AVG(_26) FROM filtered
UNION ALL
SELECT '27', AVG(_27) FROM filtered
UNION ALL
SELECT '28', AVG(_28) FROM filtered
UNION ALL
SELECT '29', AVG(_29) FROM filtered
UNION ALL
SELECT '30', AVG(_30) FROM filtered
UNION ALL
SELECT '31', AVG(_31) FROM filtered
UNION ALL
SELECT '32', AVG(_32) FROM filtered
UNION ALL
SELECT '33', AVG(_33) FROM filtered
UNION ALL
SELECT '34', AVG(_34) FROM filtered
UNION ALL
SELECT '35', AVG(_35) FROM filtered
UNION ALL
SELECT '36', AVG(_36) FROM filtered
UNION ALL
SELECT '37', AVG(_37) FROM filtered
UNION ALL
SELECT '38', AVG(_38) FROM filtered
UNION ALL
SELECT '39', AVG(_39) FROM filtered
UNION ALL
SELECT '40', AVG(_40) FROM filtered
UNION ALL
SELECT '41', AVG(_41) FROM filtered
UNION ALL
SELECT '42', AVG(_42) FROM filtered
UNION ALL
SELECT '43', AVG(_43) FROM filtered
UNION ALL
SELECT '44', AVG(_44) FROM filtered
UNION ALL
SELECT '45', AVG(_45) FROM filtered
UNION ALL
SELECT '46', AVG(_46) FROM filtered
UNION ALL
SELECT '47', AVG(_47) FROM filtered
UNION ALL
SELECT '48', AVG(_48) FROM filtered
UNION ALL
SELECT '49', AVG(_49) FROM filtered
UNION ALL
SELECT '50', AVG(_50) FROM filtered
UNION ALL
SELECT '51', AVG(_51) FROM filtered
UNION ALL
SELECT '52', AVG(_52) FROM filtered
UNION ALL
SELECT '53', AVG(_53) FROM filtered
UNION ALL
SELECT '54', AVG(_54) FROM filtered
UNION ALL
SELECT '55', AVG(_55) FROM filtered
UNION ALL
SELECT '56', AVG(_56) FROM filtered
UNION ALL
SELECT '57', AVG(_57) FROM filtered
UNION ALL
SELECT '58', AVG(_58) FROM filtered
UNION ALL
SELECT '59', AVG(_59) FROM filtered
UNION ALL
SELECT '60', AVG(_60) FROM filtered
UNION ALL
SELECT '61', AVG(_61) FROM filtered
UNION ALL
SELECT '62', AVG(_62) FROM filtered
UNION ALL
SELECT '63', AVG(_63) FROM filtered
UNION ALL
SELECT '64', AVG(_64) FROM filtered
UNION ALL
SELECT '65', AVG(_65) FROM filtered
UNION ALL
SELECT '66', AVG(_66) FROM filtered
UNION ALL
SELECT '67', AVG(_67) FROM filtered
UNION ALL
SELECT '68', AVG(_68) FROM filtered
UNION ALL
SELECT '69', AVG(_69) FROM filtered
UNION ALL
SELECT '70', AVG(_70) FROM filtered
UNION ALL
SELECT '71', AVG(_71) FROM filtered
UNION ALL
SELECT '72', AVG(_72) FROM filtered
UNION ALL
SELECT '73', AVG(_73) FROM filtered
UNION ALL
SELECT '74', AVG(_74) FROM filtered
UNION ALL
SELECT '75', AVG(_75) FROM filtered
UNION ALL
SELECT '76', AVG(_76) FROM filtered
UNION ALL
SELECT '77', AVG(_77) FROM filtered
UNION ALL
SELECT '78', AVG(_78) FROM filtered
UNION ALL
SELECT '79', AVG(_79) FROM filtered
UNION ALL
SELECT '80', AVG(_80) FROM filtered
UNION ALL
SELECT '81', AVG(_81) FROM filtered
UNION ALL
SELECT '82', AVG(_82) FROM filtered
UNION ALL
SELECT '83', AVG(_83) FROM filtered
UNION ALL
SELECT '84', AVG(_84) FROM filtered
UNION ALL
SELECT '85', AVG(_85) FROM filtered
UNION ALL
SELECT '86', AVG(_86) FROM filtered
UNION ALL
SELECT '87', AVG(_87) FROM filtered
UNION ALL
SELECT '88', AVG(_88) FROM filtered
UNION ALL
SELECT '89', AVG(_89) FROM filtered
UNION ALL
SELECT '90', AVG(_90) FROM filtered
UNION ALL
SELECT '91', AVG(_91) FROM filtered
UNION ALL
SELECT '92', AVG(_92) FROM filtered
UNION ALL
SELECT '93', AVG(_93) FROM filtered
UNION ALL
SELECT '94', AVG(_94) FROM filtered
UNION ALL
SELECT '95', AVG(_95) FROM filtered
UNION ALL
SELECT '96', AVG(_96) FROM filtered
UNION ALL
SELECT '97', AVG(_97) FROM filtered
UNION ALL
SELECT '98', AVG(_98) FROM filtered
UNION ALL
SELECT '99', AVG(_99) FROM filtered
UNION ALL
SELECT '100', 0.0;
